name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Back Repository
        uses: actions/checkout@v3

      - name: Deploy Back via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/ystudent/ystudent-back
            git pull origin main
            docker compose -f ~/ystudent/docker-compose.yml build back reverb back_nginx
            docker compose -f ~/ystudent/docker-compose.yml up -d back reverb back_nginx
            docker exec back_php php artisan migrate --force
